// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smxmahhzlzvgpkaiboxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNteG1haGh6bHp2Z3BrYWlib3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MDMxMjIsImV4cCI6MjA2MzQ3OTEyMn0.tJenXeKRzk96N72aMqozCMzw_WtAjIdrBK0gW74s1Gg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);